name: Simple Java CI with Gradle (System Gradle)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Gradle
      uses: gradle/wrapper-validation-action@v1
      with:
        gradle-version: '7.5'  # Chọn version Gradle mà bạn muốn dùng

    - name: Build with Gradle
      run: gradle build --no-daemon

    - name: Run tests
      run: gradle test --no-daemon
