name: Java CI with Ant

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Cài đặt JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Cài đặt Ant
      - name: Install Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant
          ant -version  # Kiểm tra phiên bản Ant

      # 4. Build với Ant (sử dụng build.xml bạn đã tạo)
      - name: Build with Ant
        run: |
          cd jdice_team5
          ant compile

      # 5. Chạy test nếu có (Bước này sẽ không chạy nếu chưa có cấu hình test)
      - name: Run tests with Ant
        run: |
          cd jdice_team5
          ant test
